name: Verify solutions

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - 00_python_bootcamp
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
        working-directory: ${{ matrix.module }}/hw
      - name: Run tests
        run: uv run pytest
        working-directory: ${{ matrix.module }}/hw
